### ISSUE TITLE
Set up Events

### ISSUE THREAD

**Issue by CoryDCode** [google/blockly-ios#272]
We need to implement events, to support Undo functionality and cross-platform workspace replay.

**Comment by CoryDCode** [comment]
When we take a look at the design for this, we need to look into decoupling FieldVariableLayout and WorkspaceLayoutCoordinator again. We linked them as a stop-gap, but may want to decouple them with this rework, as well.

**Comment by vicng** [comment]
NSNotifications that are being generated/listened to within Blockly iOS should most likely be refactored as part of this Events implementation (eg. MutatorProcedureDefinitionLayout, WorkspaceLayoutCoordinator, ProcedureCoordinator).

**Comment by vicng** [comment]
As part of this implementation, EventManager should combine events that are valid merge partners (eg. two move events on the same block that are part of the same group).

**Comment by vicng** [comment]
Fixed in #320, #322, #323, #328, #329, #332, #333 (phew!).

Decoupling FieldVariableLayout from WorkspaceLayoutCoordinator has been moved to its own issue #334.
