### ISSUE TITLE
Add flag to WorkbenchViewController to hide category sidebar for single-category toolboxes

### ISSUE THREAD

**Issue by vicng** [google/blockly-ios#279]
If this flag is set to true, the toolbox drawer is automatically set to always open.

**Comment by CoryDCode** [comment]
Talked with Victor about this today, and we've decided not to fix this issue for two reasons:

One - with the notch and safe space change on iOS, this will be hard to maintain and harder to style properly.

Two - Leaving the toolbox open is problematic on phones. It takes up a lot of real estate and proper constraints are difficult. We discussed other ways of opening and closing a single-category workspace, but all of our ideas were non-discoverable or different from the default for largely no reason.
