### ISSUE TITLE
Fix the variable button, so it looks nicer and is less dependent on magic numbers

### ISSUE THREAD

**Issue by CoryDCode** [google/blockly-ios#291]
The variable button in ToolboxCategoryViewController should be skinned to look like a button (probably,) and needs to be either dynamically sized such that the toolbox doesn't need to resize when variables are added, or it needs to be configurable and the toolbox needs to resize when blocks are added/removed from the variable category.

**Comment by vicng** [comment]
Fixed in #472 .
