### ISSUE TITLE
Blockly.framework contains libswiftRemoteMirror.dylib which is not permitted by app store approval system

### ISSUE THREAD

**Issue by studyfordream** [google/blockly-ios#338]
<img width="538" alt="screen shot 2017-03-27 at 12 28 22" src="https://cloud.githubusercontent.com/assets/8867233/24340973/f3297642-12e8-11e7-88ae-c26989851c3d.png">
how to solve this problem? any suggestions will be appreciated.

**Comment by vicng** [comment]
Hmm, I'm never seen this before. Have you tried taking a look at this post? http://stackoverflow.com/questions/39480526/what-is-libswiftremotemirror-dylib-and-why-is-it-being-included-in-my-app-bundle

**Comment by studyfordream** [comment]
I've tried this solution, but i failed, 😓to be honest, i'm newbie, i've searched lots of articles and then tried every answers, in the end , it still not work. I use Xcode to archive my project, extracts My.app  and  remove the libswiftRemoteMirror.dylib, then resign the My.app, it complains Blockly.framework missing some file. 
 I've also tried this tool : https://dantheman827.github.io/ios-app-signer/, it still failed.   after removing blockly dependency from my app, then i can submit my app to app store.
<img width="915" alt="screen shot 2017-03-28 at 04 28 26" src="https://cloud.githubusercontent.com/assets/8867233/24376607/0e620fa6-136f-11e7-9d87-df16d33005be.png">

I've attempted use the source code of Blockly-ios, but multiple files can not find.

**Comment by vicng** [comment]
I will try to do an app submission tomorrow to see what the problem is (unfortunately I won't be able to get to it today).

In the meantime, can you go to the "Build Settings" tab in the Blockly target (not your project target) and try setting "Always Embed Swift Standard Libraries"  to "No"?

![screen shot 2017-03-27 at 4 41 13 pm](https://cloud.githubusercontent.com/assets/13488389/24382650/769476da-130c-11e7-8a49-87ed4c95c691.png)

**Comment by studyfordream** [comment]
thank you very much. I remember that way i've tried.  I will try again. Thank you Sir 🙏

**Comment by studyfordream** [comment]
I set the "Always Embed ..." to NO, and create new workspace, drag blockly to the new workspace , and  it can be permitted to submit now. Thank you, sir.🙂

**Comment by vicng** [comment]
That's good to hear!

Have you built an app with Blockly iOS? If so, we'd love it if you could share a link with us when it gets approved -- we're curious to see how developers are using it (to see what feature to build, improve, etc).

**Comment by studyfordream** [comment]
OK, I will share a link when it gets approved. I just embed Blockly iOS into my app simply and directly, in the future, i will study how to make our clients to love it, to use blockly as their first programming language.

**Comment by studyfordream** [comment]
Hi, sir, out blockly app has been issued to app store, you can search for "代码课"。this is the first release to show how we use the great blockly, for future, we will think how to improve our idea. we very appreciate for any advices come.

**Comment by vicng** [comment]
Thanks for sharing your app with us. We're always looking to see how our developers are using Blockly and what improvements can be made. If you don't mind filling out this [questionnaire](https://goo.gl/forms/kZTsO9wGLmpoPXC02), it'd help us figure out what to work on next.

As for advice, we suggest that you post your questions on the [Blockly developer forum](https://groups.google.com/forum/#!forum/blockly). We read that forum regularly and are happy to provide help, but there's also a large community that may be able to provide further insight for any app-specific design questions.
