### ISSUE TITLE
Error when loading default blocks

### ISSUE THREAD

**Issue by cartmanguo** [google/blockly-ios#348]
I install the latest develop branch(with localization support) with cocoapods,this error message shows up when I use
`blockFactory.load(fromDefaultFiles: .allDefault)`
![image](https://cloud.githubusercontent.com/assets/4699162/24739416/7ec7c338-1ace-11e7-97b5-d5c883c5502e.png)

**Comment by vicng** [comment]
Just created PR #349 to address this issue. It should be in the "develop" branch shortly (or you could get it from the "vn-1-cocoapods" branch in the meantime).

**Comment by vicng** [comment]
The fix has been merged into the develop branch now.
