### ISSUE TITLE
Duplicate function call when loading functions from XML

### ISSUE THREAD

**Issue by fzzr-** [google/blockly-ios#379]
Problem in the process when we resolving a relationship of `caller ->- definition`.

I think definition created before it added to `definitionBlocks`. I think this happens because in resolving process the passage through the tree top-down in depth but not in the opposite direction.

Workspace for reproduce:
![screen shot 2017-04-26 at 18 22 03](https://cloud.githubusercontent.com/assets/888526/25442414/aa7325ec-2aad-11e7-9f83-ccb82de8c247.png)

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xml xmlns="http://www.w3.org/1999/xhtml">
	<block x="232" id="3A8D7297-0A72-410D-9D05-F7A6673100D8" type="procedures_defnoreturn" y="30">
		<mutation statements="true" />
		<field name="NAME">do something</field>
		<statement name="STACK">
			<block type="procedures_callnoreturn" id="060CF615-D4CB-4C10-A9DA-75290C2AC0FB">
				<mutation name="do something" />
			</block>
		</statement>
	</block>
</xml>
```

- - -

![blockly-funcs-resolve-issue mov](https://cloud.githubusercontent.com/assets/888526/25442768/967874ec-2aae-11e7-8cb4-add80f7e637e.gif)

**Comment by CoryDCode** [comment]
I can confirm this bug - simply add the following code to the TurtleSwiftViewController, and the result is a duplicate "do something" procedure call.

`try! _workbenchViewController.workspace?.loadBlocks(fromXMLString: "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>      <xml xmlns=\"http://www.w3.org/1999/xhtml\">      <block x=\"232\" id=\"3A8D7297-0A72-410D-9D05-F7A6673100D8\" type=\"procedures_defnoreturn\" y=\"30\">      <mutation statements=\"true\" />      <field name=\"NAME\">do something</field>      <statement name=\"STACK\">      <block type=\"procedures_callnoreturn\" id=\"060CF615-D4CB-4C10-A9DA-75290C2AC0FB\">      <mutation name=\"do something\" />      </block>      </statement>      </block>      </xml>", factory: _workbenchViewController.blockFactory)`

![screen shot 2017-05-01 at 10 03 35 am](https://cloud.githubusercontent.com/assets/13773511/25586724/78b6f104-2e55-11e7-8c09-edb1d680e28f.png)
