### ISSUE TITLE
BlocklySample[3078:747821] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

### ISSUE THREAD

**Issue by studyfordream** [google/blockly-ios#382]
when load this block file into workspace, it print the title message on console.

**Comment by studyfordream** [comment]
<xml xmlns="http://www.w3.org/1999/xhtml"><block type="turtle_pen" id="J5rvD*5lr{[wMP5Oj(iC" x="119" y="-5"><field name="PEN">penUp</field><next><block type="turtle_move" id="f=o;GOku.jw,W|IH!N32"><field name="DIR">moveForward</field><value name="VALUE"><shadow type="math_number" id="tS~valW[i.%6c~rN~]^M"><field name="NUM">185</field></shadow></value><next><block type="turtle_turn" id="vpMU90wLOTQlnE]FRJ!P"><field name="DIR">turnRight</field><value name="VALUE"><shadow type="math_number" id="h01drbaZWZG]sEX__uwT"><field name="NUM">90</field></shadow></value><next><block type="turtle_move" id="Ph+M!6~K3VR}exE`L)p6"><field name="DIR">moveForward</field><value name="VALUE"><shadow type="math_number" id="`xV{!;93]A/N1up#)mSN"><field name="NUM">20</field></shadow></value><next><block type="turtle_turn" id=";GN;tsuJ-Nf.4n;QV7@D"><field name="DIR">turnLeft</field><value name="VALUE"><shadow type="math_number" id="S+|gU6faex2%/aD#Vv)A"><field name="NUM">90</field></shadow></value><next><block type="turtle_pen" id="Ww]s.~y?B#H.8rC=]1tu"><field name="PEN">penDown</field><next><block type="turtle_width" id="F.~*(vWtyl0kPf1=y)0i"><value name="WIDTH"><shadow type="math_number" id="M,fH^EGg_`I!Vxy##,72"><field name="NUM">2</field></shadow></value><next><block type="controls_repeat_ext" id="h480u3ViYr%}6[)a95@O"><value name="TIMES"><shadow type="math_number" id="SehAQrto{*y)BfTkRlg{"><field name="NUM">40</field></shadow></value><statement name="DO"><block type="turtle_colour" id="h2ykT9dcSU!7[{Ir]A39"><value name="COLOUR"><shadow type="colour_picker" id="{8J+EXIUE:pQ@%HonXqW"><field name="COLOUR">#33ccff</field></shadow></value><next><block type="controls_repeat_ext" id="BaI.rhz3X:7~4W/;zyar"><value name="TIMES"><shadow type="math_number" id="8J|G]:Bl-%a0cVbWn/U0"><field name="NUM">100</field></shadow></value><statement name="DO"><block type="turtle_turn" id="M%bmPaoI`jGDQ!oF6]6N"><field name="DIR">turnLeft</field><value name="VALUE"><shadow type="math_number" id="7`1@6EMQz9=H~[n1ndS!"><field name="NUM">1111111111</field></shadow><block type="math_constant" id="R]qK=DdAA~Su)A=aj1|%"><field name="CONSTANT">GOLDEN_RATIO</field></block></value></block></statement><next><block type="controls_repeat_ext" id="AY/IXhxEq1=yy9BECeul"><value name="TIMES"><shadow type="math_number" id="hcH}0PjKXETom%2Rxohq"><field name="NUM">20</field></shadow></value><statement name="DO"><block type="turtle_move" id="s;R:EFx%@PW`.S@O9s(3"><field name="DIR">moveForward</field><value name="VALUE"><shadow type="math_number" id="SbnVb57la#7r+SgH/4(h"><field name="NUM">15</field></shadow></value><next><block type="turtle_turn" id="17Jo8cc_dfkZmkvofP0+"><field name="DIR">turnRight</field><value name="VALUE"><shadow type="math_number" id="7`1@6EMQz9=H~[n1ndS!"><field name="NUM">1111111111</field></shadow><block type="math_constant" id="J!lqVwDp(+BVn)B:Ey]o"><field name="CONSTANT">PI</field></block></value></block></next></block></statement></block></next></block></next></block></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>

**Comment by vicng** [comment]
Two blocks in the XML are using the same ID, which is not allowed (`7`1@6EMQz9=H~[n1ndS!`).

If you change one of the blocks to use a different ID, then it should work.
