### ISSUE TITLE
iOS 11 "WKWebView.evaluateJavaScript(_:completionHandler:) must be used from main thread only" Fix

### ISSUE THREAD

**Issue by happyBear9** [google/blockly-ios#452]
Hi all,
I updated my OS to iOS11 today and my blocky apps immediately failed to generate code. However you will not get any build issues. I'm using blockylV1.0 and code generation from my block code failed with above stated error. This also seems to be the problem with V1.1.1's samples. I did however find a quick fix but not sure if its the right way. Since the error says 

> WKWebView.evaluateJavaScript(_:completionHandler:) must be used from main thread only

 I figured it needs to be dispatched to the main thread... here's how I did it.

if the CodeGenerator.swift file, around line 210

```
    DispatchQueue.main.async(execute: {
        self.webView.evaluateJavaScript(js, completionHandler: { (_, error) -> Void in
            if let error = error {
                self.codeGenerationFailed("An error occurred generating code: \(error)")
            }
    })
        
```
This solved the problem and the equivalent code is properly generated. Let me know if this is valid. Thanks a lot!

**Comment by vicng** [comment]
Thanks for pointing this out and thanks for giving the solution too :)

Fixed in #453 .
