### ISSUE TITLE
When my Xcode update to xcode9 appear this problem:WKWebView.evaluateJavaScript(_:completionHandler:) must be used from main thread .what should I do?

### ISSUE THREAD

**Issue by XXyueliang** [google/blockly-ios#498]
![snip20171208_1](https://user-images.githubusercontent.com/29173407/33746322-5501df8a-dbf7-11e7-9c48-b3d8428cdc96.png)

**Comment by vicng** [comment]
It appears you are using an older version of Blockly. This bug was fixed in #453 .  I'd recommend updating to the latest version, which will fix this bug along with many others.
