### ISSUE TITLE
bug: orientation is not respected

### ISSUE THREAD

**Issue by gaming-hacker** [google/blockly-ios#503]
all,

i built music maker demo for ipad with landscape L/R only and the initial hardware rotation is landscape left but the display is oriented in portrait.
if you rotate the device, the orientation is then correct.

**Comment by vicng** [comment]
I wasn't able to repro this. Perhaps it's a simulator bug? I'm running Xcode 9.2.

**Comment by gaming-hacker** [comment]
ah, yes sorry forgot about that, yes simulator.   please close.
