### ISSUE TITLE
zoom  WorkbenchViewController.swift  ToolboxCategoryViewController

### ISSUE THREAD

**Issue by tangzhifengjluzh** [google/blockly-ios#510]
How to fix the custom block of the Toolbox Category ViewController without being scaled when scaling the Workbench ViewController workspace

**Comment by tangzhifengjluzh** [comment]
![image](https://user-images.githubusercontent.com/16828896/58367454-fb5f2900-7f11-11e9-8fbb-63a341d3c2fd.png)

**Comment by tangzhifengjluzh** [comment]
How to make the block of the toolbox not follow the zoom when zooming the workspace

**Comment by RoboErikG** [comment]
Please ask these kinds of questions on [the forum](https://groups.google.com/forum/?pli=1#!forum/blockly). The issue tracker is for bugs or feature requests.
